---
{
  'kind': 'pipeline',
  'name': 'Kubernetes',
  'node_selector': { 'drone': true },
  'platform': { 'arch': 'amd64', 'os': 'linux' },
  'steps':
    [
      {
        'commands':
          [
            'npm install prettier',
            'npx prettier --check "**/*.{ts,js,md,yaml,yml,sass,css,scss}"',
          ],
        'image': 'node:lts-buster',
        'name': 'Prettier lint',
        'pull': 'always',
      },
      {
        'commands':
          [
            'npm install elm-analyse elm-format',
            'npx elm-analyse',
            'npx elm-format --validate src/',
          ],
        'image': 'node:lts-buster',
        'name': 'Elm lint',
        'pull': 'always',
      },
      {
        'image': 'banzaicloud/drone-kaniko:0.5.1',
        'name': 'Build container image',
        'pull': 'always',
        'trigger': { 'event': ['pull_request'] },
        'when': { 'branch': { 'exclude': ['master'] } },
      },
      {
        'image': 'banzaicloud/drone-kaniko:0.5.1',
        'name': 'Publish image kradalby/resume',
        'pull': 'always',
        'settings':
          {
            'password': { 'from_secret': 'docker_password' },
            'repo': 'kradalby/resume',
            'tags':
              [
                'latest',
                'latest-${DRONE_STAGE_OS}-${DRONE_STAGE_ARCH}',
                '${DRONE_COMMIT_SHA:0:8}',
              ],
            'username': { 'from_secret': 'docker_username' },
          },
        'when': { 'branch': ['master'], 'event': ['push'] },
      },
      {
        'commands':
          [
            'container-file-extractor "kradalby/resume" "${DRONE_COMMIT_SHA:0:8}" "usr/share/nginx/html"',
            'mkdir -p dist/',
            'mv output/usr/share/nginx/html/* dist/.',
          ],
        'image': 'kradalby/container-file-extractor:latest',
        'name': 'Extract from container',
        'pull': 'always',
        'when': { 'branch': ['master'], 'event': ['push'] },
      },
      {
        'image': 'plugins/gh-pages',
        'name': 'Publish to GitHub Pages',
        'pull': 'always',
        'settings':
          {
            'pages_directory': 'dist',
            'password': { 'from_secret': 'github_pages_push_token' },
            'username': { 'from_secret': 'github_pages_push_user' },
          },
        'when': { 'branch': ['master'], 'event': ['push'] },
      },
      {
        'image': 'appleboy/drone-discord',
        'name': 'Notify Discord',
        'pull': 'always',
        'settings':
          {
            'message': "{{#success build.status}}\n✅  Build #{{build.number}} of `{{repo.name}}` succeeded.\n\n📝  Commit by {{commit.author}} on `{{commit.branch}}`:\n``` {{commit.message}} ```\n🌐  {{ build.link }}\n\n✅  duration: {{duration build.started build.finished}}\n✅  started: {{datetime build.started \"2006/01/02 15:04\" \"UTC\"}}\n✅  finished: {{datetime build.finished \"2006/01/02 15:04\" \"UTC\"}}\n\n{{else}}\n@everyone\n❌  Build #{{build.number}} of `{{repo.name}}` failed.\n\n📝  Commit by {{commit.author}} on `{{commit.branch}}`:\n``` {{commit.message}} ```\n🌐  {{ build.link }}\n\n✅  duration: {{duration build.started build.finished}}\n✅  started: {{datetime build.started \"2006/01/02 15:04\" \"UTC\"}}\n✅  finished: {{datetime build.finished \"2006/01/02 15:04\" \"UTC\"}}\n\n{{/success}}\n",
            'webhook_id': { 'from_secret': 'discord_webhook_id' },
            'webhook_token': { 'from_secret': 'discord_webhook_token' },
          },
        'when': { 'status': ['success', 'failure'] },
      },
    ],
  'type': 'kubernetes',
}
