---
kind: pipeline
type: kubernetes
name: default

node_selector:
  drone: 'true'

steps:
  - name: lint
    pull: if-not-exists
    image: node:10
    commands:
      - make install
      - make lint

  - name: build
    pull: always
    image: plugins/docker
    environment:
      DOCKER_BUILDKIT: 1
    settings:
      repo: dryrun
      dry_run: true

  - name: publish
    pull: always
    image: plugins/docker
    environment:
      DOCKER_BUILDKIT: 1
    settings:
      repo: kradalby/resume
      tags:
        - ${DRONE_COMMIT_SHA:0:8}
        - latest
      cache: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      branch:
        - master
      event:
        - push

  - name: deploy
    pull: if-not-exists
    image: kradalby/drone-kubectl
    environment:
      KUBERNETES_CERT:
        from_secret: kubernetes_cert
      KUBERNETES_SERVER:
        from_secret: kubernetes_server
      KUBERNETES_TOKEN:
        from_secret: kubernetes_token
    commands:
      - kubectl -n resume set image deployment/resume common=kradalby/resume:${DRONE_COMMIT_SHA:0:8} --record
      - kubectl -n resume rollout status deployment resume
    when:
      branch:
        - master
      event:
        - push

  - name: notify
    pull: if-not-exists
    image: drillster/drone-email
    settings:
      from: drone@drone.fap.no
      host: smtp.fap.no
      port: 25
      recipients:
        - kradalby@kradalby.no
      skip_verify: true
    when:
      status:
        - success
        - changed
        - failure
