---
{
   "kind": "pipeline",
   "name": "default",
   "node_selector": {
      "drone": true
   },
   "steps": [
      {
         "commands": [
            "make install",
            "make lint"
         ],
         "image": "node:10",
         "name": "Node lint",
         "pull": "always"
      },
      {
         "image": "banzaicloud/drone-kaniko:0.5.1",
         "name": "Build container image",
         "pull": "always",
         "when": {
            "branch": {
               "exclude": [
                  "master"
               ]
            }
         }
      },
      {
         "image": "banzaicloud/drone-kaniko:0.5.1",
         "name": "Publish image kradalby/resume",
         "pull": "always",
         "settings": {
            "password": {
               "from_secret": "docker_password"
            },
            "repo": "kradalby/resume",
            "tags": [
               "latest",
               "${DRONE_COMMIT_SHA:0:8}"
            ],
            "username": {
               "from_secret": "docker_username"
            }
         },
         "when": {
            "branch": [
               "master"
            ],
            "event": [
               "push"
            ]
         }
      },
      {
         "commands": [
            "kubectl -n $APP set image deployment/$APP $APP=$REPO:${DRONE_COMMIT_SHA:0:8} --record",
            "kubectl -n $APP rollout status deployment $APP"
         ],
         "environment": {
            "APP": "resume",
            "KUBERNETES_CERT": {
               "from_secret": "kubernetes_cert"
            },
            "KUBERNETES_SERVER": {
               "from_secret": "kubernetes_server"
            },
            "KUBERNETES_TOKEN": {
               "from_secret": "kubernetes_token"
            },
            "REPO": "kradalby/resume"
         },
         "image": "kradalby/drone-kubectl",
         "name": "Deploy resume to Kubernetes",
         "pull": "always",
         "when": {
            "branch": [
               "master"
            ],
            "event": [
               "push"
            ]
         }
      },
      {
         "image": "appleboy/drone-discord",
         "name": "Notify Discord",
         "pull": "always",
         "settings": {
            "message": "{{#success build.status}} ✅  Build #{{build.number}} of `{{repo.name}}` succeeded.\n\n📝 Commit by {{commit.author}} on `{{commit.branch}}`:\n``` {{commit.message}} ```\n🌐 {{ build.link }}\n\n ✅ duration: {{duration build.started build.finished}} \n\n ✅ started: {{datetime build.started \"2006/01/02 15:04\" \"UTC\"}} \n\n ✅ finished: {{datetime build.finished \"2006/01/02 15:04\" \"UTC\"}} {{else}} ❌  Build #{{build.number}} of `{{repo.name}}` failed.\n\n📝 Commit by {{commit.author}} on `{{commit.branch}}`:\n``` {{commit.message}} ```\n🌐 {{ build.link }}\n\n ✅ duration: {{duration build.started build.finished}} \n\n ✅ started: {{datetime build.started \"2006/01/02 15:04\" \"UTC\"}} \n\n ✅ finished: {{datetime build.finished \"2006/01/02 15:04\" \"UTC\"}}{{/success}}\n",
            "webhook_id": {
               "from_secret": "discord_webhook_id"
            },
            "webhook_token": {
               "from_secret": "discord_webhook_token"
            }
         },
         "when": {
            "status": [
               "success",
               "failure"
            ]
         }
      }
   ],
   "type": "kubernetes"
}
---
{
   "get": {
      "name": "id",
      "path": "discord-build"
   },
   "kind": "secret",
   "name": "discord_webhook_id"
}
---
{
   "get": {
      "name": "token",
      "path": "discord-build"
   },
   "kind": "secret",
   "name": "discord_webhook_token"
}
---
{
   "get": {
      "name": "username",
      "path": "docker"
   },
   "kind": "secret",
   "name": "docker_username"
}
---
{
   "get": {
      "name": "password",
      "path": "docker"
   },
   "kind": "secret",
   "name": "docker_password"
}
...
