workspace:
  base: /go/src/github.com/kradalby/resume

pipeline:
  lint: 
    image: node:10
    commands: 
        - make install
        - make lint
  build:
    image: plugins/docker
    repo: kradalby/resume
    # auto_tag: true
    secrets: [ docker_username, docker_password ]
    tags:
        - ${DRONE_COMMIT_SHA:0:8}
        - latest

  deploy:
     image: quay.io/honestbee/drone-kubernetes
     deployment: resume-deployment
     repo: kradalby/resume
     container: resume-container
     namespace: resume
     secrets: [ kubernetes_server, kubernetes_cert, kubernetes_token ]
     tag:
       - ${DRONE_COMMIT_SHA:0:8}

  notify:
    image: drillster/drone-email
    host: smtp.fap.no
    skip_verify: true
    port: 25
    from: drone@drone.fap.no
    recipients: [ kradalby@kradalby.no ]
    when:
      status: [ success, changed, failure ]
