# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
  pull_request:
    branches:
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v18

      - name: Install dependencies
        run: nix develop --command -- make install

      - name: Run build
        run: nix develop --command -- make build

      - name: Run render
        run: nix develop --command -- xvfb-run yarn electron-pdf $GITHUB_WORKSPACE/dist/index.html $GITHUB_WORKSPACE/dist/resume.pdf

      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          cname: resume.kradalby.no
